version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: ['./docker/entrypoint.sh', "db:5432"]
  
  db:
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./dbdata:/var/lib/postgresql/data:cached
  
  pgadmin:
    image: dpage/pgadmin4
    links:
      - db
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pwdpwd
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
