name: Build and Deploy Local Docker

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: eddymena19/iaapi

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t $IMAGE_NAME:latest .

      - name: Run Docker Compose
        run: |
          echo "Starting services with Docker Compose..."
          docker-compose down || true
          docker-compose up -d

      - name: List running containers
        run: |
          docker ps
