name: Build, Test & Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  IMAGE_NAME: eddymena19/iaapi

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Run lightweight Python test
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install pytest
          mkdir -p tests
          echo "def test_example(): assert 1 + 1 == 2" > tests/test_sample.py
          pytest tests

      - name: Start Docker Compose services
        run: |
          docker-compose down || true
          docker-compose up -d

      - name: List running containers
        run: docker ps

      - name: SonarCloud analysis
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=EddyMena_iaapiTestEnv
            -Dsonar.organization=eddymena19
            -Dsonar.host.url=https://sonarcloud.io
