name: Deploy

on:
  push:
    branches:
      - master
env:
  IMAGE_NAME: eddymena19/iaapi

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest
    environment: login
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - name: Deploy service with traefik over ssh
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
          eval $(ssh-agent -s)
          echo "add ssh key"
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" $SSH_USER@$SSH_HOST "
            export DB_HOST=${DB_HOST}
            export DB_PORT=${DB_PORT}
            export DB_CONNECTION=${DB_CONNECTION}
            export SECRET_KEY=${SECRET_KEY}
            
            cd /var/www/iaapi && \
            git pull && \
            (docker stack rm iaapi-services || true) && \
            (docker swarm leave --force || true) && \
            docker swarm init --advertise-addr 10.19.0.6 && \
            docker stack deploy -c docker-compose.yml iaapi-services && \
            docker stack ls && \
            docker service ls && \
            docker container ls"