name: Build and Deploy Local Docker

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: eddymena19/iaapi

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout the repo
      - uses: actions/checkout@v3

      # 2️⃣ Fix case-sensitive file issues
      - name: Fix Git case sensitivity
        run: |
          git config core.ignorecase false
          git ls-files -i -o --exclude-standard  # just to show untracked/ignored files
          # optionally you could delete and re-add files with wrong case here
          
      # 3️⃣ Set up Docker Buildx
      - uses: docker/setup-buildx-action@v2

      # 4️⃣ Log in to Docker Hub
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5️⃣ Build Docker image
      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t $IMAGE_NAME:latest .

      # 6️⃣ Run Docker Compose
      - name: Run Docker Compose
        run: |
          echo "Starting services with Docker Compose..."
          docker compose down || true
          docker compose up -d

      # 7️⃣ List running containers
      - name: List running containers
        run: docker ps
